/**
 * I3oT-Pro-API
 * I3oT-Pro API for I3oT developer
 *
 * OpenAPI spec version: 1.0.0
 * Contact: i3ot@kuangyibang.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface AllDlt645AddInfo { 
    id?: number;
    recordAdd?: string;
    localModbusAdd?: string;
    addName?: string;
    addUnit?: string;
    formula?: string;
}