/**
 * I3oT-Pro-API
 * I3oT-Pro API for I3oT developer
 *
 * OpenAPI spec version: 1.0.0
 * Contact: i3ot@kuangyibang.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */import { AllDlt645AddInfo } from './allDlt645AddInfo';


export interface InlineResponse2003 { 
    statusCode?: number;
    description?: string;
    resData?: Array<AllDlt645AddInfo>;
}